CREATE (a:Thing {name:'A'})
CREATE (b:Thing:P {name:'B'})
CREATE (c:Thing:Q {name:'C'})
CREATE (d:Thing:P:Q {name:'D'})
CREATE (a)-[:X]->(b)
CREATE (a)-[:X]->(b)
CREATE (a)-[:Y]->(b)
CREATE (a)<-[:X]-(b)
CREATE (a)<-[:X]-(b)
CREATE (a)<-[:Y]-(b)
CREATE (a)-[:X]->(c)
CREATE (a)-[:X]->(c)
CREATE (a)-[:Y]->(c)
CREATE (a)<-[:X]-(c)
CREATE (a)<-[:X]-(c)
CREATE (a)<-[:Y]-(c)
CREATE (c)-[:X]->(c)
CREATE (c)-[:Y]->(c)
CREATE (c)-[:X]->(d)
CREATE (c)-[:X]->(d)
CREATE (c)-[:Y]->(d)
CREATE (c)<-[:X]-(d)
CREATE (c)<-[:X]-(d)
CREATE (c)<-[:Y]-(d)
